Epoch 0:   0%|          | 0/120 [00:00<?, ?it/s]Epoch 0:   0%|          | 0/120 [00:11<?, ?it/s]
Traceback (most recent call last):
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 685, in <module>
    main()
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 641, in main
    trainer.train()
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 552, in train
    epoch_loss, epoch_dice, epoch_hd, epoch_nsd, epoch_dice_loss, epoch_ce_loss = self.train_epoch(epoch, np.random.randint(1, 21))
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 487, in train_epoch
    prev_masks, loss, dice_loss, ce_loss = self.interaction(
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 380, in interaction
    low_res_masks, prev_masks = self.batch_forward(
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/train.py", line 325, in batch_forward
    low_res_masks, iou_predictions = sam_model.mask_decoder(
  File "/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sammed3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/dss/dsshome1/0D/ru47tac2/miniconda3/envs/sammed3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/segment_anything/modeling/mask_decoder3D.py", line 365, in forward
    masks, iou_pred = self.predict_masks(
  File "/dss/dsshome1/0D/ru47tac2/projects/segrap2025/SAM-Med3D/segment_anything/modeling/mask_decoder3D.py", line 422, in predict_masks
    masks = (hyper_in @ upscaled_embedding.view(b, c, x * y * z)).view(b, -1, x, y, z)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [1, 3] but got: [1, 48].
